services:
  app:
    build: .
    ports:
      - "8081:8081"
    ### env_file:
    ###  - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/otp_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - otp-network

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=otp_db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - otp-network

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - otp-network

volumes:
  postgres_data:
  redis_data:

networks:
  otp-network:
    driver: bridge
